### ISSUE TITLE
[META] v0.3 – First release with Airstream

### ISSUE THREAD

**Issue by raquo** [raquo/Laminar#13]
This is what I plan to release in the next version, v0.3, probably/hopefully in a couple weeks.

### Features
- [x] Initial development of Airstream
- [x] Replace XStream with Airstream in Laminar
- [x] Laminar: Rename `bundle` object to `L` to make it feasible to avoid importing a million DOM names.
- [x] Laminar/SDB/SDT: Fix for meta modifier support in light of 2.12 SAM magic – see https://github.com/raquo/scala-dom-types/issues/27

### Chores
- [x] Move Airstream into a separate package, and publish it to Maven Central
- [x] Publish the half-baked TodoMVC app that I have in a private laminar-examples project

### Docs
- [x] Write initial Airstream docs
- [x] Update Laminar documentation with all the new features and changes (incl. #9)

### Things that will not make it to v0.3 (up for debate)
- [ ] Airstream error handling (not implemented, exceptions are pretty much undefined behavior)
- [ ] Airstream helpers for dealing with async data structures (Futures / etc.), e.g. `mapFuture`, `Future.toEventStream`, etc.
- [ ] Airstream: Create `combine` and `map` methods for N=3
- [ ] Laminar/SDB: Make setParent and other internal methods more private
- [ ] Docs: Add a Cheatsheet section for Laminar
- [ ] Docs: Add a Cheatsheet section for Airstream

**Comment by ngbinh** [comment]
AirStream looks awesome. Definitely something we can use internally even without Laminar.

**Comment by raquo** [comment]
@ngbinh Thanks! FYI I just published Airstream v0.1 in a separate repo: https://github.com/raquo/Airstream

**Comment by raquo** [comment]
Alright, Laminar v0.3 and Airstream v0.2 are out along with a massive Laminar documentation update 🎉
